### ISSUE TITLE
查成绩龟速

### ISSUE THREAD

**Issue by Nukepayload2** [sdzxwxlsj/NWU_Grade#1]
为啥查成绩那么慢呢？服务器的问题？

**Comment by ewfian** [comment]
因为那个sql语句占满了一页屏幕

**Comment by kkwpsv** [comment]
查询所有成绩的接口比较慢，查询当前学期的接口很快，wcf后面代码看不到，原因不好说。我这个项目用的是查询当前学期成绩的接口，应该不存在这个问题吧？

**Comment by Nukepayload2** [comment]
@sdzxwxlsj 哦，那应该是服务器的问题。2 楼正解。

**Comment by Nukepayload2** [comment]
@sdzxwxlsj GetMyGrades 确实更慢。

**Comment by Nukepayload2** [comment]
我似乎知道为啥 GetMyGrades 更慢了。这个查询包括绩点和学年。

**Comment by HarborZeng** [comment]
几天没看，就水了这么多
